# Label configuration for GitHub Actions labeler

bug:
  - '.*[Bb]ug.*'
  - '.*[Ee]rror.*'
  - '.*[Ff]ix.*'
  - '.*not working.*'
  - '.*broken.*'

enhancement:
  - '.*[Ff]eature.*'
  - '.*[Ee]nhancement.*'
  - '.*[Ii]mprovement.*'
  - '.*[Aa]dd.*'
  - '.*[Nn]ew.*'

docs:
  - '.*[Dd]oc.*'
  - '.*[Rr]eadme.*'
  - '.*[Gg]uide.*'
  - '.*[Tt]utorial.*'

question:
  - '.*[Qq]uestion.*'
  - '.*[Hh]elp.*'
  - '.*[Hh]ow to.*'
  - '.*\?.*'
