# Label configuration for GitHub Actions labeler

bug:
  - '/(bug|error|fix|not working|broken)/i'

enhancement:
  - '/(feature|enhancement|improvement|add|new)/i'

docs:
  - '/(doc|readme|guide|tutorial)/i'

question:
  - '/(question|help|how to|\?)/i'
