exclude_path = [
    "./docs/adr", # ADRs are not part of the core documentation
    "./docs/blog", # Let's not check blog links for now
    "./website/versioned*", # Focus on next version
    "./website/static/download/downloads.html", # Should we fix in the future?
    "./dev/rc-email-template.md", # Should we fix in the future?
    "./qdp/docs/readers/README.md", # TODO: fix the links in this file
]
fallback_extensions = ["md"]
