import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Apache Mahout Documentation Sidebars
 *
 * The docs are synced from /docs at build time via sync-docs.js
 * This sidebar configuration uses auto-generated sidebars based on folder structure.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar - auto-generated from docs folder structure
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
